name: Scheduled run

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]
  workflow_dispatch:

env:
  COURSES: "IngegneriaInformatica informatica"


jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Run
        run: go run ./cmd ${{ env.COURSES }}

      - name: Prepare Pages artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: rss

  deploy:
    # Add a dependency to the build job
    needs: run

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: "pages"
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
